### ISSUE TITLE
ToggleDisplay Util doesn't work when compiling by myself

### ISSUE THREAD

**Issue by alanlomeli** [sgrottel/tiny-tools-collection#70]
Hello! 
I was wondering if you could provide some insight, as your provided exe file seems to be working fine for enabling the displays. However if I compile myself the displays won't change, whether is enabling or disabling, the displays flash but the mode wont change.
The enumeration of the displays is correct. Is there something I might be missing? 
Using visual studio 2022 toolchain v143
Thanks for the utility

**Comment by alanlomeli** [comment]
Using the branch with logging, I'm getting this information:
![image](https://github.com/user-attachments/assets/7ea42083-3fa9-43a7-b314-9a55440b93e8)

[ToggleDisplay.log](https://github.com/user-attachments/files/17236152/ToggleDisplay.log)

**Comment by sgrottel** [comment]
Hi Alanlomeli, thank you for reaching out.
So, the exactly same command line with the same arguments work with the ToggleDisplay.exe downloaded from Github, but not with the one you built yourself? That is super strange, and should (obviously) not be the case.

From the log you provided I see that the Selected Path is good. It's a full configuration struct as it should be. Sadly, there is a bug with the error result reporting. Can you please switch to this branch: `toggledisplay-fix-error-messages`?
There, it should correctly report the error result, instead of unicode garbage.

**Comment by alanlomeli** [comment]
Thanks for your response.
Actually from this build I managed to switch my other monitors, only one for some reason seems to be problematic.. getting ERROR_GEN_FAILURE So I guess it's 
[ToggleDisplay: ERROR_GEN_FAILURE](https://github.com/sgrottel/tiny-tools-collection/issues/23#top)
#23 
![image](https://github.com/user-attachments/assets/9fd7e4df-2de4-436f-a647-cbd860776dc1)
[ToggleDisplay.log](https://github.com/user-attachments/files/17248148/ToggleDisplay.log)

**Comment by sgrottel** [comment]
So, you now get the same error behavior with the executable you built yourself and with the executable downloaded from here, from Github?

Another possible error source might be: if you DISABLE this one display now manually, via the GUI dialog, enable it again, and then run ToggleDisplay.exe to do the same, does it still not work?

(Windows seems to have an issue when enabling/disabling/toggling a display will results in a configuration of active displays which it has never seen before...)

**Comment by sgrottel** [comment]
I am now closing this issue for lack of updates. I assume the issue has been fixed or a workaround has been found. If not, of course, feel free to open the issue again with updated information.
